

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.webadmin.*  #springbean监控
      filters: stat,wall,slf4j  #所有开启的功能

      stat-view-servlet:  #监控页配置
        enabled: true
        login-username: root
        login-password: root
        resetEnable: false

      web-stat-filter:  #web监控
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter:
        stat: #sql监控
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall: #防火墙
          enabled: true
          config:
            # 禁止删除表的操作，所有删除表的操作都会被防火墙拦截
            drop-table-allow: false
  jdbc:
    template:
      query-timeout: 3
  # redis
  redis:
    host: r-bp1pm01e5ctdy3tr43pd.redis.rds.aliyuncs.com
    port: 6379
    password: ljc:Ljc18830860332
    client-type: jedis
    jedis:
      pool:
        max-active: 10
  # 监控view相关
  boot:
    admin:
      client:
        url: http://localhost:8888
        instance:
          prefer-ip: true  #使用ip注册进来
  application:
    name: web-admin


# mybatis
#mybatis:
##  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
#  # 全局配置文件，如果配置了这个就不能指定config-location: classpath:mybatis/mybatis-config.xml，二者选一
#  configuration:
#    map-underscore-to-camel-case: true

# management 是所有actuator的配置
# management.endpoint.端点名.xxxx  对某个端点的具体配置
management:
  endpoints:
    enabled-by-default: true  #默认开启所有监控端点  true
    web:
      exposure:
        include: '*' # 以web方式暴露所有端点

  endpoint:   #对某个端点的具体配置, 选择性开启某个端点
    health:
      show-details: always
      enabled: true

    info:
      enabled: true

    beans:
      enabled: true

    metrics:
      enabled: true
# 访问：http://localhost:8080/actuator/info
info:
  appName: boot-admin
  appVersion: 1.0.0
  mavenProjectName: @project.artifactId@
  mavenProjectVersion: @project.version@